path: '/content/drive/MyDrive/data_coin/uploads'
train: '/content/drive/MyDrive/data_coin/uploads/train'
val: '/content/drive/MyDrive/data_coin/uploads/test'

names:
  0: '1_cent'
  1: '2_cent'
  2: '5_cent'
  3: '10_cent'
  4: '20_cent'
  5: '50_cent'
  6: '1_euro'
  7: '2_euro'



# Augmentation
fliplr: 0.0
mosaic: 0.6
mixup: 0.0
