path: '/content/drive/MyDrive/data_coin/uploads'
train: '/content/drive/MyDrive/data_coin/uploads/images/train'
val: '/content/drive/MyDrive/data_coin/uploads/images/test'

names:
  7: '1_cent'
  6: '2_cent'
  5: '5_cent'
  4: '10_cent'
  3: '20_cents'
  2: '50_cents'
  1: '1_euro'
  0: '2_euro'



# Augmentation
fliplr: 0.0
mosaic: 0.6
mixup: 0.0
