path: '/content/drive/MyDrive/data_coin/uploads'
train: '/content/drive/MyDrive/data_coin/uploads/train'
val: '/content/drive/MyDrive/data_coin/uploads/test'

names:
  11: '1_cent'
  10: '2_cent'
  9: '5_cent'
  8: '10_cent'
  7: '20_cents'
  6: '50_cents'
  5: '1_euro'
  4: '2_euro'
  3: 'truc1',
  2: 'truc2',
  1: 'truc3',
  0: 'truc4'



# Augmentation
fliplr: 0.0
mosaic: 0.6
mixup: 0.0
